spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

sentry:
  dsn: ${SENTRY_DSN:https://30b8b419abdaa2cc1a915fb2b9937b6d@o4511431330955264.ingest.us.sentry.io/4511431349895168}
  environment: production
  traces-sample-rate: 0.0

springdoc:
  swagger-ui:
    enabled: false
  api-docs:
    enabled: false

logging:
  level:
    root: WARN
    com.starterkit: INFO
